#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2014 OpenWrt.org

START=94
STOP=13
USE_PROCD=1

pre_set()
{
	[ "$(uci get network.wan.ifname)" != "$1" ] && {
		uci set network.wwan5g='interface'
		uci set network.wwan5g.ifname="$1"
		uci set network.wwan5g.proto='dhcp'
		if [ "$ipv6" = 1 ]; then
			uci set network.wwan5g6='interface'
			uci set network.wwan5g6.ifname="$1"
			uci set network.wwan5g6.proto='dhcpv6'
			uci set network.wwan5g6.extendprefix='1'
		fi
		uci commit network

		num=`uci show firewall |grep "name='wan'" |wc -l`
		wwan5g_num=`uci get firewall.@zone[$num].network |grep -w wwan5g |wc -l`
		wwan5g6_num=`uci get firewall.@zone[$num].network |grep -w wwan5g6 |wc -l`
		if [ "$wwan5g_num" = "0" ]; then
			uci add_list firewall.@zone[$num].network='wan'
		fi
		if [ "$ipv6" = 1 ]; then
			if [ "$wwan5g6_num" = "0" ]; then
				uci add_list firewall.@zone[$num].network='wwan5g6'
			fi
		fi
		uci commit firewall

		ifup wwan5g
		if [ "$ipv6" = 1 ]; then
			ifup wwan5g6
		fi
	}

	[ "$(uci get network.wan6.ifname)" == "$1" ] && {
		uci set network.wan6.extendprefix='1'
		uci commit network
	}
}

run_dial()
{
	local enabled
	config_get_bool enabled $1 enabled

	if [ "$enabled" = "1" ]; then
		local apn
		local user
		local password
		local auth
		local ipv6
		local device

		config_get apn $1 apn
		config_get user $1 user
		config_get password $1 password
		config_get auth $1 auth
		config_get ipv6 $1 ipv6
		config_get device $1 device

		devname="$(basename "$device")"
		devicepath="$(find /sys/class/ -name $devname)"
		devpath="$(readlink -f $devicepath/device/)"
		ifname="$( ls "$devpath"/net )"

		procd_open_instance
		procd_set_param command quectel-CM
		if [ "$ipv6" = 1 ]; then
			procd_append_param command -4 -6
		fi
		if [ "$apn" != "" ];then
			procd_append_param command -s $apn
		fi
		if [ "$user" != "" ]; then
			procd_append_param command $user
		fi
		if [ "$password" != "" ]; then
			procd_append_param command $password
		fi
		if [ "$auth" != "" ]; then
			procd_append_param command $auth
		fi
		if [ "$device" != "" ]; then
			procd_append_param command -i $ifname
		fi
		procd_set_param respawn
		procd_close_instance

		if [ -d /sys/class/net/rmnet_mhi0 ]; then
			pre_set rmnet_mhi0.1
		elif [ -d /sys/class/net/wwan0_1 ]; then
			pre_set wwan0_1
		elif [ -d /sys/class/net/wwan0.1 ]; then
			pre_set wwan0.1
		elif [ -d /sys/class/net/wwan0 ]; then
			pre_set wwan0
		fi
	fi

	sleep 15
}

service_triggers()
{
	procd_add_reload_trigger "hypermodem"
}

start_service() {
	config_load hypermodem
	config_foreach run_dial service
}

stop_service()
{
	killall quectel-CM >/dev/null 2>&1
}

auto_reconnect() {
    local check_interval=35  # 检查间隔，单位秒
    local ip_addresses=("119.29.29.29" "223.5.5.5" "1.2.4.8")  # 需要检测的IP列表
    local interface="wwan5g"  # 指定要用来ping的接口

    while true; do
        for ip in "${ip_addresses[@]}"; do
            if ping -I "$interface" -c 1 -w 5 "$ip" > /dev/null 2>&1; then
                echo "网络通过 $ip 连接正常"
                break 2  # 跳出整个循环
            fi
        done

        modem_reset  # 调用重置网络连接的函数
        sleep "$check_interval"  # 等待一定时间后再次检测
    done
}

# 定义重置网络连接的函数
modem_reset() {
    echo "正在停止所有 quectel-CM 进程..."
    killall quectel-CM >/dev/null 2>&1
    sleep 1  # 等待几秒确保进程已经完全终止

    echo "正在停止 hypermodem 服务..."
    /etc/init.d/hypermodem stop
    sleep 1  # 等待几秒确保服务已经完全停止

    echo "正在启动 hypermodem 服务..."
    /etc/init.d/hypermodem start
    echo "hypermodem 服务重启完毕。"
}
